name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.14"]

    steps:
      - uses: "actions/checkout@v6"
        with:
          fetch-depth: 0

      - uses: "astral-sh/setup-uv@v6"
        with:
          enable-cache: true

      - uses: "actions/setup-python@v6"
        with:
            python-version: "${{ matrix.python-version }}"

      - name: "Install nox"
        run: uv tool install nox

      - name: "Run nox for ${{ matrix.python-version }}"
        run: "nox -db uv -s test-${{ matrix.python-version }} -- --cov-report lcov:lcov-${{matrix.os}}-${{matrix.python-version}}.lcov --cov-report term --cov-append --cov scitrack"

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{matrix.python-version}}-${{matrix.os}}
          file: "tests/lcov-${{matrix.os}}-${{matrix.python-version}}.lcov"

  finish:
    name: "Finish Coveralls"
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true