name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.14"]

    steps:
      - uses: "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1" # v7.0.1
        with:
          fetch-depth: 0

      - uses: "astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990" # v8.3.2
        with:
          enable-cache: true

      - uses: "actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1" # v6.3.0
        with:
            python-version: "${{ matrix.python-version }}"

      - name: "Install nox"
        run: uv tool install nox

      - name: "Run nox for ${{ matrix.python-version }}"
        run: "nox -db uv -s test-${{ matrix.python-version }} -- --cov-report lcov:lcov-${{matrix.os}}-${{matrix.python-version}}.lcov --cov-report term --cov-append --cov scitrack"


      - name: trust coveralls (macOS)
        if: runner.os == 'macOS'
        run: |
          brew trust coverallsapp/coveralls

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{matrix.python-version}}-${{matrix.os}}
          file: "tests/lcov-${{matrix.os}}-${{matrix.python-version}}.lcov"

  finish:
    name: "Finish Coveralls"
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true