name: CI

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} (${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.14"]

    steps:
      - uses: "actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0" # v7.0.0
        with:
          fetch-depth: 0

      - uses: "astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9" # v9.0.0
        with:
          enable-cache: true

      - uses: "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97" # v7.0.0
        with:
            python-version: "${{ matrix.python-version }}"

      - name: "Install nox"
        run: uv tool install nox

      - name: "Run nox for ${{ matrix.python-version }}"
        run: "nox -db uv -s test-${{ matrix.python-version }} -- --cov-report lcov:lcov-${{matrix.os}}-${{matrix.python-version}}.lcov --cov-report term --cov-append --cov scitrack"


      - name: trust coveralls (macOS)
        if: runner.os == 'macOS'
        run: |
          brew trust coverallsapp/coveralls

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
        with:
          parallel: true
          github-token: ${{ secrets.github_token }}
          flag-name: run-${{matrix.python-version}}-${{matrix.os}}
          file: "tests/lcov-${{matrix.os}}-${{matrix.python-version}}.lcov"

  finish:
    name: "Finish Coveralls"
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2.3.7
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true